### ISSUE TITLE
Dragonbreath crashes client on 1.10

### ISSUE THREAD

**Issue by sphinxc0re** [mathiascode/ParticleTrails#1]
<img width="946" alt="screen shot 2017-03-26 at 15 58 52" src="https://cloud.githubusercontent.com/assets/3702016/24331874/3a05c95a-123d-11e7-98cf-8802851731aa.png">
<img width="966" alt="screen shot 2017-03-26 at 15 58 49" src="https://cloud.githubusercontent.com/assets/3702016/24331873/38ad4858-123d-11e7-9e94-af957e2feb6a.png">

**Comment by mathiascode** [comment]
How old is your Cuberite build? This should be fixed in builds after https://github.com/cuberite/cuberite/commit/65ee749013795eb70f9069537ce0767b673755c8 (including the endrod particle bug).
